### ISSUE TITLE
See if we can use travis_retry in the CI

### ISSUE THREAD

**Issue by rhysmeister** [ansible-collections/community.mongodb#178]
##### SUMMARY

See if we can avoid the occasional failures we see in the travis CI with the travis_retry function detailed here...

https://docs.travis-ci.com/user/common-build-problems/

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
travis_run.sh

**Comment by cognifloyd** [comment]
https://docs.travis-ci.com/user/common-build-problems/#travis_retry

We can use this for some of the steps in `.travis.yml`, but I don't think it makes sense to use it in `run_travis.sh` because molecule already takes awhile.

I also think we can do something like this to resolve timeouts in github workflows:
```yaml
- name: Install community.general
  run: "for i in {1..3}; do ansible-galaxy collection install community.general -p ../../ && break || sleep 5; done"
```

**Comment by cognifloyd** [comment]
Another way to speed things up and avoid all these network timeouts with ansible-galaxy might be to cache the collections for some period of time (a day?).

This looks like a good option for the github workflows: https://github.com/marketplace/actions/cache
Maybe there's another good action as well.

**Comment by rhysmeister** [comment]
> Another way to speed things up and avoid all these network timeouts with ansible-galaxy might be to cache the collections for some period of time (a day?).
> 
> This looks like a good option for the github workflows: https://github.com/marketplace/actions/cache
> Maybe there's another good action as well.

How does that work exactly? Can the cache be shared across all jobs in a CI run? I can't see any examples using pip/rpm(npm etc. If there's a way of making it work I would imagine even a cache per run improving things.

**Comment by cognifloyd** [comment]
Found a pip example:
https://github.com/actions/cache/blob/main/examples.md#python---pip

We pick the cache key(s), so for pip we could use the ansible version (since that's what we're installing with pip in the github workflow). For galaxy, we could use maybe a commit hash?

Thinking this through, we could explicitly populate a new cache before running the integration tests. Add a new job to make the cache, and then use `needs` so integration doesn't run unless the cache populates successfully. For that perhaps we could use the commit hash as the key.

https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

**Comment by rhysmeister** [comment]
OK. A clear win.

I was thinking along these lines but for the rpm/deb files we download. We pull down a fair few MB for each job when we install MongoDB.

**Comment by rhysmeister** [comment]
No longer relevant.
