### ISSUE TITLE
mongo_config and mongo_mongod config files have the same name/path

### ISSUE THREAD

**Issue by gwbischof** [ansible-collections/community.mongodb#197]
Hi, I am really happy that I found this repo.  I was planning on writing something similar from scratch.
I'll try to contribute if I discover any problems, fixes, improvements during my testing.

I noticed that both of these config files get written to the same place. So they will overwrite each other if installed on the same machine. Is this intentional?
https://github.com/ansible-collections/community.mongodb/blob/master/roles/mongodb_mongod/tasks/main.yml#L39
https://github.com/ansible-collections/community.mongodb/blob/master/roles/mongodb_config/tasks/main.yml#L34

**Comment by rhysmeister** [comment]
Hello, yes that's intentional. It's best practice not to deploy your config servers on the mongod shard servers.

**Comment by cognifloyd** [comment]
Hmm. I wonder if the `mongodb_config` role should be renamed? When I first opened it, I did not know what a mongo config server was. I assumed from the name that that role added the mongod.conf file. I was confused when it did so much more.

Is there a better name that says "this installs a config server" instead of "this configures the mongod"?
Maybe `mongodb_csrs`?

**Comment by rhysmeister** [comment]
I think it's pretty obvious what it is, especially in context with the other roles, but then I'm a DBA! Although I'd assume config servers are unlikely to change anytime soon they used to be mirrored copies, rather than today's replicaset. So mongodb_config would be futureproof in the unlikely event that were to change. Just my two cents.

**Comment by cognifloyd** [comment]
I'm not a DBA. I'm in DevOps and install Mongo as a dependency for other software. So, this collection was my first exposure to the concept of a "config server". To me config = the conf file.

**Comment by cognifloyd** [comment]
@gwbischof Did you have same first impression as I did? Or were you expecting the `mongodb_config` role to install a config server?

**Comment by gwbischof** [comment]
I thought is was to install a config server, the beginning of the readme says that it is for a config server.
I don't remember what my impression was before I read the readme.

**Comment by gwbischof** [comment]
I think l want to install the config server on the same machines as the shard server, I only have 3 machines to work with.  I think I'll make some adjustments on my fork to get it to work.
